#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';
use Data::Dump qw/pp/;
use Teach::Tutor;

my ($start, $inc, $max) = @ARGV;

die "$0 called with unvalid arguments\n"
   unless @ARGV==3 and ($start < $max) && $inc;

for (my($num,$i)=($start,0); $num<=$max; $i++) {
   $num +=$i*$inc;
   say $num; 
}

#say pp($str);
#submit($str);
