#!/usr/bin/perl

use strict;
use warnings;
use Teach::Tutor;
use Data::Dump 'pp';
use feature 'say';

my %person = (
  'Action'  => "Says",
  'Subject' => "Wash your hands!",
  'Weight'  => "75kg",
  'Height'  => "190cm",
  'Name'    => "Simon",
);

unless (scalar(@ARGV) && 
  (($ARGV[0] =~ /^(keys|values)$/))
  ) {
  say "$0 must be called with a single command-line argument - 
  'keys' or 'values'";
  exit;
}

my $arg = shift;

my @outlist = sort ($arg eq 'keys' ? keys %person : values %person);

submit(@outlist);
say pp(@outlist);
