#!/usr/bin/perl

use strict;
use warnings;
use Data::Dump 'pp';
use feature 'say';
use Getopt::Long;

my $filename = '/home/student/perl-basic/topic-07/iata_airports.csv';
my $number = 1;
my $matching; #string
my $word;  #false
my($latitude, $longitude);

GetOptions(
    'filename=s'    => \$filename,
    'number=i'      => \$number,
    'matching=s'    => \$matching,
    'word'          => \$word,
    'latitude=f'    => \$latitude,
    'longitude=f'   => \$longitude,
) or die "bad args!\n";

if ($matching) {
  say "Up to $number airports matching $matching in $filename:";
}
elsif ($latitude && $longitude) {
  say "Up to $number airports near [$latitude, $longitude] in $filename:"
}
else {
  say "Must have at least --matching, or --latitude and --longitude as arguments";
}
