#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';
use Data::Dump 'pp';

use FurnitureShop;
use FurnitureShop::Chair;
use FurnitureShop::Table;

say FurnitureShop::hello('fred');
say FurnitureShop::Chair->sell('fred');
say FurnitureShop::Table->sell('fred');

