#!/usr/bin/perl
use strict;
use warnings;
use feature 'say';

sub greet_friend {
    my $rh_friend = {
        age     => 5,
        reading => 'Encyclopedia Britannica',
        @_
  };

  return sprintf(
      "Hi %s! I'm %d and I read %s ages ago. Totally boring."
      . " But I like %s as a hobby%s",
      $rh_friend->{name},
      $rh_friend->{age} + 1,
      $rh_friend->{reading},
      $rh_friend->{hobby},
      exists $rh_friend->{diet} ? " and $rh_friend->{diet} as a diet." : "."
  );
}

say greet_friend(
  name    => 'Daniela',
  age     => 16,
  reading => 'Shakespeare',
  hobby   => 'Pac Man',
  diet    => 'Vegan',
);
